package CATS::Countries;

my $flags_path = './images/countries/';

our @countries = (
{ id => 'zz', flag => undef, name => 'Non-UN entity or any other territory' },
{ id => 'AF', flag => 'af.gif', name => 'Afghanistan' },
{ id => 'AL', flag => 'al.gif', name => 'Albania' },
{ id => 'DZ', flag => 'dz.gif', name => 'Algeria' },
{ id => 'AD', flag => 'ad.gif', name => 'Andorra' },
{ id => 'AO', flag => 'ao.gif', name => 'Angola' },
{ id => 'AG', flag => 'ag.gif', name => 'Antigua and Barbuda' },
{ id => 'AE', flag => 'ae.gif', name => 'Arab Emirates' },
{ id => 'AR', flag => 'ar.gif', name => 'Argentina' },
{ id => 'AM', flag => 'am.gif', name => 'Armenia' },
{ id => 'AU', flag => 'au.gif', name => 'Australia' },
{ id => 'AT', flag => 'at.gif', name => 'Austria' },
{ id => 'AZ', flag => 'az.gif', name => 'Azerbaijan' },
{ id => 'BS', flag => 'bs.gif', name => 'Bahamas' },
{ id => 'BH', flag => 'bh.gif', name => 'Bahrain' },
{ id => 'BD', flag => 'bd.gif', name => 'Bangladesh' },
{ id => 'BB', flag => 'bb.gif', name => 'Barbados' },
{ id => 'BY', flag => 'by.gif', name => 'Belarus' },
{ id => 'BE', flag => 'be.gif', name => 'Belgium' },
{ id => 'BZ', flag => 'bz.gif', name => 'Belize' },
{ id => 'BJ', flag => 'bj.gif', name => 'Benin' },
{ id => 'BT', flag => 'bt.gif', name => 'Bhutan' },
{ id => 'BO', flag => 'bo.gif', name => 'Bolivia' },
{ id => 'BA', flag => 'ba.gif', name => 'Bosnia and Herzegovina' },
{ id => 'BW', flag => 'bw.gif', name => 'Botswana' },
{ id => 'BR', flag => 'br.gif', name => 'Brazil' },
{ id => 'BN', flag => 'bn.gif', name => 'Brunei' },
{ id => 'BG', flag => 'bg.gif', name => 'Bulgaria' },
{ id => 'BF', flag => 'bf.gif', name => 'Burkina Faso' },
{ id => 'BI', flag => 'bi.gif', name => 'Burundi' },
{ id => 'CV', flag => 'cv.gif', name => 'Cape Verde' },
{ id => 'KH', flag => 'kh.gif', name => 'Cambodia' },
{ id => 'CM', flag => 'cm.gif', name => 'Cameroon' },
{ id => 'CA', flag => 'ca.gif', name => 'Canada' },
{ id => 'CF', flag => 'cf.gif', name => 'Central Africa' },
{ id => 'TD', flag => 'td.gif', name => 'Chad' },
{ id => 'CL', flag => 'cl.gif', name => 'Chile' },
{ id => 'CN', flag => 'cn.gif', name => 'China' },
{ id => 'CO', flag => 'co.gif', name => 'Colombia' },
{ id => 'KM', flag => 'km.gif', name => 'Comoros' },
{ id => 'CG', flag => 'cg.gif', name => 'Congo-Brazzaville' },
{ id => 'CD', flag => 'cd.gif', name => 'Congo-Kinshasa' },
{ id => 'CR', flag => 'cr.gif', name => 'Costa Rica' },
{ id => 'HR', flag => 'hr.gif', name => 'Croatia' },
{ id => 'CU', flag => 'cu.gif', name => 'Cuba' },
{ id => 'CY', flag => 'cy.gif', name => 'Cyprus' },
{ id => 'CZ', flag => 'cz.gif', name => 'Czechia' },
{ id => 'DK', flag => 'dk.gif', name => 'Denmark' },
{ id => 'DJ', flag => 'dj.gif', name => 'Djibouti' },
{ id => 'DM', flag => 'dm.gif', name => 'Dominica' },
{ id => 'DO', flag => 'do.gif', name => 'Dominicana' },
{ id => 'EC', flag => 'ec.gif', name => 'Ecuador' },
{ id => 'EG', flag => 'eg.gif', name => 'Egypt' },
{ id => 'SV', flag => 'sv.gif', name => 'El Salvador' },
{ id => 'GQ', flag => 'gq.gif', name => 'Equatorial Guinea' },
{ id => 'ER', flag => 'er.gif', name => 'Eritrea' },
{ id => 'EE', flag => 'ee.gif', name => 'Estonia' },
{ id => 'ET', flag => 'et.gif', name => 'Ethiopia' },
{ id => 'FJ', flag => 'fj.gif', name => 'Fiji' },
{ id => 'FI', flag => 'fi.gif', name => 'Finland' },
{ id => 'FR', flag => 'fr.gif', name => 'France' },
{ id => 'GA', flag => 'ga.gif', name => 'Gabon' },
{ id => 'GM', flag => 'gm.gif', name => 'Gambia' },
{ id => 'GE', flag => 'ge.gif', name => 'Georgia' },
{ id => 'DE', flag => 'de.gif', name => 'Germany' },
{ id => 'GH', flag => 'gh.gif', name => 'Ghana' },
{ id => 'GB', flag => 'gb.gif', name => 'Great Britain' },
{ id => 'GR', flag => 'gr.gif', name => 'Greece' },
{ id => 'GD', flag => 'gd.gif', name => 'Grenada' },
{ id => 'GT', flag => 'gt.gif', name => 'Guatemala' },
{ id => 'GN', flag => 'gn.gif', name => 'Guinea' },
{ id => 'GW', flag => 'gw.gif', name => 'Guinea-Bissau' },
{ id => 'GY', flag => 'gy.gif', name => 'Guyana' },
{ id => 'HT', flag => 'ht.gif', name => 'Haiti' },
{ id => 'HN', flag => 'hn.gif', name => 'Honduras' },
{ id => 'HU', flag => 'hu.gif', name => 'Hungary' },
{ id => 'IS', flag => 'is.gif', name => 'Iceland' },
{ id => 'IN', flag => 'in.gif', name => 'India' },
{ id => 'ID', flag => 'id.gif', name => 'Indonesia' },
{ id => 'IR', flag => 'ir.gif', name => 'Iran' },
{ id => 'IQ', flag => 'iq.gif', name => 'Iraq' },
{ id => 'IE', flag => 'ie.gif', name => 'Ireland' },
{ id => 'IL', flag => 'il.gif', name => 'Israel' },
{ id => 'IT', flag => 'it.gif', name => 'Italy' },
{ id => 'CI', flag => 'ci.gif', name => 'Ivory Coast' },
{ id => 'JM', flag => 'jm.gif', name => 'Jamaica' },
{ id => 'JP', flag => 'jp.gif', name => 'Japan' },
{ id => 'JO', flag => 'jo.gif', name => 'Jordan' },
{ id => 'KZ', flag => 'kz.gif', name => 'Kazakhstan' },
{ id => 'KE', flag => 'ke.gif', name => 'Kenya' },
{ id => 'KI', flag => 'ki.gif', name => 'Kiribati' },
{ id => 'KP', flag => 'kp.gif', name => 'Korea (North)' },
{ id => 'KR', flag => 'kr.gif', name => 'Korea (South)' },
{ id => 'KW', flag => 'kw.gif', name => 'Kuwait' },
{ id => 'KG', flag => 'kg.gif', name => 'Kyrgyzstan' },
{ id => 'LA', flag => 'la.gif', name => 'Laos' },
{ id => 'LV', flag => 'lv.gif', name => 'Latvia' },
{ id => 'LB', flag => 'lb.gif', name => 'Lebanon' },
{ id => 'LS', flag => 'ls.gif', name => 'Lesotho' },
{ id => 'LR', flag => 'lr.gif', name => 'Liberia' },
{ id => 'LY', flag => 'ly.gif', name => 'Libya' },
{ id => 'LI', flag => 'li.gif', name => 'Liechtenstein' },
{ id => 'LT', flag => 'lt.gif', name => 'Lithuania' },
{ id => 'LU', flag => 'lu.gif', name => 'Luxembourg' },
{ id => 'MK', flag => 'mk.gif', name => 'Macedonia' },
{ id => 'MG', flag => 'mg.gif', name => 'Madagascar' },
{ id => 'MW', flag => 'mw.gif', name => 'Malawi' },
{ id => 'MY', flag => 'my.gif', name => 'Malaysia' },
{ id => 'MV', flag => 'mv.gif', name => 'Maldives' },
{ id => 'ML', flag => 'ml.gif', name => 'Mali' },
{ id => 'MT', flag => 'mt.gif', name => 'Malta' },
{ id => 'MH', flag => 'mh.gif', name => 'Marshall Islands' },
{ id => 'MR', flag => 'mr.gif', name => 'Mauritania' },
{ id => 'MU', flag => 'mu.gif', name => 'Mauritius' },
{ id => 'MX', flag => 'mx.gif', name => 'Mexico' },
{ id => 'FM', flag => 'fm.gif', name => 'Micronesia' },
{ id => 'MD', flag => 'md.gif', name => 'Moldova' },
{ id => 'MC', flag => 'mc.gif', name => 'Monaco' },
{ id => 'MN', flag => 'mn.gif', name => 'Mongolia' },
{ id => 'ME', flag => 'me.gif', name => 'Montenegro' },
{ id => 'MA', flag => 'ma.gif', name => 'Morocco' },
{ id => 'MZ', flag => 'mz.gif', name => 'Mozambique' },
{ id => 'MM', flag => 'mm.gif', name => 'Myanmar' },
{ id => 'NA', flag => 'na.gif', name => 'Namibia' },
{ id => 'NR', flag => 'nr.gif', name => 'Nauru' },
{ id => 'NP', flag => 'np.gif', name => 'Nepal' },
{ id => 'NL', flag => 'nl.gif', name => 'Netherlands' },
{ id => 'NZ', flag => 'nz.gif', name => 'New Zealand' },
{ id => 'NI', flag => 'ni.gif', name => 'Nicaragua' },
{ id => 'NE', flag => 'ne.gif', name => 'Niger' },
{ id => 'NG', flag => 'ng.gif', name => 'Nigeria' },
{ id => 'NO', flag => 'no.gif', name => 'Norway' },
{ id => 'OM', flag => 'om.gif', name => 'Oman' },
{ id => 'PK', flag => 'pk.gif', name => 'Pakistan' },
{ id => 'PW', flag => 'pw.gif', name => 'Palau' },
{ id => 'PA', flag => 'pa.gif', name => 'Panama' },
{ id => 'PG', flag => 'pg.gif', name => 'Papua New Guinea' },
{ id => 'PY', flag => 'py.gif', name => 'Paraguay' },
{ id => 'PE', flag => 'pe.gif', name => 'Peru' },
{ id => 'PH', flag => 'ph.gif', name => 'Philippines' },
{ id => 'PL', flag => 'pl.gif', name => 'Poland' },
{ id => 'PT', flag => 'pt.gif', name => 'Portugal' },
{ id => 'QA', flag => 'qa.gif', name => 'Qatar' },
{ id => 'RO', flag => 'ro.gif', name => 'Romania' },
{ id => 'RU', flag => 'ru.gif', name => 'Russia' },
{ id => 'RW', flag => 'rw.gif', name => 'Rwanda' },
{ id => 'KN', flag => 'kn.gif', name => 'St. Kitts and Nevis' },
{ id => 'LC', flag => 'lc.gif', name => 'St. Lucia' },
{ id => 'VC', flag => 'vc.gif', name => 'St. Vincent and the Grenadines' },
{ id => 'WS', flag => 'ws.gif', name => 'Samoa' },
{ id => 'SM', flag => 'sm.gif', name => 'San Marino' },
{ id => 'ST', flag => 'st.gif', name => 'St. Thomas and Prince' },
{ id => 'SA', flag => 'sa.gif', name => 'Saudi Arabia' },
{ id => 'SN', flag => 'sn.gif', name => 'Senegal' },
{ id => 'RS', flag => 'rs.gif', name => 'Serbia' },
{ id => 'SC', flag => 'sc.gif', name => 'Seychelles' },
{ id => 'SL', flag => 'sl.gif', name => 'Sierra Leone' },
{ id => 'SG', flag => 'sg.gif', name => 'Singapore' },
{ id => 'SK', flag => 'sk.gif', name => 'Slovakia' },
{ id => 'SI', flag => 'si.gif', name => 'Slovenia' },
{ id => 'SB', flag => 'sb.gif', name => 'Solomon Islands' },
{ id => 'SO', flag => 'so.gif', name => 'Somalia' },
{ id => 'ZA', flag => 'za.gif', name => 'South Africa' },
{ id => 'SD', flag => 'sd.gif', name => 'Sudan (North)' },
{ id => 'SS', flag => undef, name => 'Sudan (South)' },
{ id => 'ES', flag => 'es.gif', name => 'Spain' },
{ id => 'LK', flag => 'lk.gif', name => 'Sri Lanka' },
{ id => 'SR', flag => 'sr.gif', name => 'Suriname' },
{ id => 'SZ', flag => 'sz.gif', name => 'Swaziland' },
{ id => 'SE', flag => 'se.gif', name => 'Sweden' },
{ id => 'CH', flag => 'ch.gif', name => 'Switzerland' },
{ id => 'SY', flag => 'sy.gif', name => 'Syria' },
{ id => 'TJ', flag => 'tj.gif', name => 'Tajikistan' },
{ id => 'TZ', flag => 'tz.gif', name => 'Tanzania' },
{ id => 'TH', flag => 'th.gif', name => 'Thailand' },
{ id => 'TL', flag => 'tl.gif', name => 'Timor-Leste' },
{ id => 'TG', flag => 'tg.gif', name => 'Togo' },
{ id => 'TO', flag => 'to.gif', name => 'Tonga' },
{ id => 'TT', flag => 'tt.gif', name => 'Trinidad and Tobago' },
{ id => 'TN', flag => 'tn.gif', name => 'Tunisia' },
{ id => 'TR', flag => 'tr.gif', name => 'Turkey' },
{ id => 'TM', flag => 'tm.gif', name => 'Turkmenistan' },
{ id => 'TV', flag => 'tv.gif', name => 'Tuvalu' },
{ id => 'UG', flag => 'ug.gif', name => 'Uganda' },
{ id => 'UA', flag => 'ua.gif', name => 'Ukraine' },
{ id => 'US', flag => 'us.gif', name => 'United States' },
{ id => 'UY', flag => 'uy.gif', name => 'Uruguay' },
{ id => 'UZ', flag => 'uz.gif', name => 'Uzbekistan' },
{ id => 'VU', flag => 'vu.gif', name => 'Vanuatu' },
{ id => 'VE', flag => 've.gif', name => 'Venezuela' },
{ id => 'VN', flag => 'vn.gif', name => 'Vietnam' },
{ id => 'YE', flag => 'ye.gif', name => 'Yemen' },
{ id => 'ZM', flag => 'zm.gif', name => 'Zambia' },
{ id => 'ZW', flag => 'zw.gif', name => 'Zimbabwe' },
{ id => 'xx', flag => 'fam.gif', name => 'I\'m an alien intellect' },
);

sub get_flag {
    my ($country_id) = @_ or return;
    my ($country) = grep $_->{id} eq $country_id, @countries or return;
    my $flag = defined $country->{flag} ? "$flags_path$country->{flag}" : undef;
    return ($country->{name}, $flag);
}

1;
