SET TERM # ;
EXECUTE BLOCK AS
    DECLARE VARIABLE CONSTR_NAME VARCHAR(100);
BEGIN
    SELECT DISTINCT CC.RDB$CONSTRAINT_NAME
    FROM RDB$TRIGGERS TR
        INNER JOIN RDB$CHECK_CONSTRAINTS CC ON TR.RDB$TRIGGER_NAME = CC.RDB$TRIGGER_NAME
    WHERE RDB$RELATION_NAME = 'PROBLEMS' AND TR.RDB$TRIGGER_SOURCE = 'CHECK (run_method IN (0, 1))' INTO :CONSTR_NAME;
    EXECUTE STATEMENT 'ALTER TABLE PROBLEMS DROP CONSTRAINT ' || :CONSTR_NAME;
    SUSPEND;
END#
SET TERM ; #

ALTER TABLE problems ADD CONSTRAINT chk_run_method CHECK (run_method IN (0, 1, 2))
