SET TERM # ;
EXECUTE BLOCK AS
    DECLARE VARIABLE constr_name VARCHAR(100);
BEGIN
    SELECT DISTINCT RDB$CONSTRAINT_NAME
        FROM RDB$RELATION_CONSTRAINTS RC
        INNER JOIN RDB$INDICES IDX ON IDX.RDB$INDEX_NAME = RC.RDB$INDEX_NAME
        INNER JOIN RDB$INDICES FK ON FK.RDB$INDEX_NAME = IDX.RDB$FOREIGN_KEY
        WHERE RC.RDB$RELATION_NAME = 'ACCOUNT_TOKENS' AND FK.RDB$RELATION_NAME = 'ACCOUNTS'
        INTO :constr_name;
    EXECUTE STATEMENT 'ALTER TABLE account_tokens DROP CONSTRAINT ' || :constr_name;
    SUSPEND;
END#
SET TERM ; #
COMMIT;

ALTER TABLE account_tokens ADD CONSTRAINT account_tokens_accounts_fk
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;
