/*--------------------------------------------------------------
**  User Defined Function definitions for CATS
**--------------------------------------------------------------
*/

DROP EXTERNAL FUNCTION CATS_DATE;
DROP EXTERNAL FUNCTION CATS_TO_DATE;
DROP EXTERNAL FUNCTION CATS_EXACT_DATE;
DROP EXTERNAL FUNCTION CATS_TO_EXACT_DATE;
DROP EXTERNAL FUNCTION CATS_DIFF_TIME;
DROP EXTERNAL FUNCTION CATS_SYSDATE;


DECLARE EXTERNAL FUNCTION CATS_DATE
    TIMESTAMP BY DESCRIPTOR 
    RETURNS CSTRING(32) FREE_IT
    ENTRY_POINT 'fn_cats_date' MODULE_NAME 'cats_udf_lib';

DECLARE EXTERNAL FUNCTION CATS_TO_DATE
    VARCHAR(100)
    RETURNS TIMESTAMP FREE_IT
    ENTRY_POINT 'fn_cats_to_date' MODULE_NAME 'cats_udf_lib';

DECLARE EXTERNAL FUNCTION CATS_EXACT_DATE
    TIMESTAMP BY DESCRIPTOR 
    RETURNS CSTRING(32) FREE_IT
    ENTRY_POINT 'fn_cats_exact_date' MODULE_NAME 'cats_udf_lib';

DECLARE EXTERNAL FUNCTION CATS_TO_EXACT_DATE
    VARCHAR(100)
    RETURNS TIMESTAMP FREE_IT
    ENTRY_POINT 'fn_cats_to_exact_date' MODULE_NAME 'cats_udf_lib';

DECLARE EXTERNAL FUNCTION CATS_DIFF_TIME
    TIMESTAMP, TIMESTAMP
    RETURNS DOUBLE PRECISION BY VALUE
    ENTRY_POINT 'fn_cats_difftime' MODULE_NAME 'cats_udf_lib';

DECLARE EXTERNAL FUNCTION CATS_SYSDATE
    RETURNS TIMESTAMP FREE_IT
    ENTRY_POINT 'fn_cats_sysdate' MODULE_NAME 'cats_udf_lib';

COMMIT;

EOF