<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
<meta name="Content-Type" content="text/html; charset=<TMPL_VAR encoding>">
<link rel="shortcut icon" href="images/std/favicon.ico" type="image/x-icon" />
<title><TMPL_IF contest_title><TMPL_VAR contest_title ESCAPE=HTML><TMPL_ELSE>CATS</TMPL_IF><TMPL_IF title_suffix> - <TMPL_VAR title_suffix></TMPL_IF></title>
<TMPL_IF printable><style type="text/css"><TMPL_INCLUDE '../docs/std/main.css'></style><TMPL_ELSE
><link rel="stylesheet" type="text/css" href="docs/std/main.css"></TMPL_IF>
