<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
<meta name="Content-Type" content="text/html; charset=<TMPL_VAR encoding>">
<title><TMPL_IF contest_title><TMPL_VAR contest_title ESCAPE=HTML><TMPL_ELSE>CATS</TMPL_IF> <TMPL_VAR title_suffix></title>
<TMPL_IF printable><style><TMPL_INCLUDE '../docs/std/main.css'></style><TMPL_ELSE
><link rel="stylesheet" type="text/css" href="./docs/std/main.css"></TMPL_IF>
