<tr><td><b>Команда:</b></td><td><b><TMPL_VAR team_name ESCAPE=HTML></b></td></tr>
<tr><td>Поставлено в очередь:</td><td><TMPL_VAR submit_time ESCAPE=HTML></td></tr>
<tr><td>Начало обработки:</td><td><TMPL_VAR test_time ESCAPE=HTML></td></tr>
<tr><td>Окончание обработки:</td><td><TMPL_VAR result_time ESCAPE=HTML></td></tr>
<tr><td>Чемпионат:</td><td><a href="<TMPL_VAR href_contest_problems>"><TMPL_VAR contest_name ESCAPE=HTML></a></td></tr>
<tr><td>Судья:</td><td><TMPL_VAR judge_name ESCAPE=HTML></td></tr>
