<script type="text/javascript" src="synh/scripts/shCore.js"></script>
<TMPL_IF unsupported>
<script type="text/javascript" src="synh/scripts/shBrushBash.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushCss.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushDiff.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushGroovy.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushJScript.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushPhp.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushScala.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushSql.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushXml.js"></script>
</TMPL_IF>
<script type="text/javascript" src="synh/scripts/shBrushCpp.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushCSharp.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushDelphi.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushJava.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushPerl.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushPlain.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushPython.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushRuby.js"></script>
<script type="text/javascript" src="synh/scripts/shBrushVb.js"></script>
<link type="text/css" rel="stylesheet" href="synh/styles/shCore.css"/>
<link type="text/css" rel="stylesheet" href="synh/styles/shThemeDefault.css" title="default"/>
<link type="text/css" rel="alternate stylesheet" href="synh/styles/shThemeDjango.css" title="django"/>
<link type="text/css" rel="alternate stylesheet" href="synh/styles/shThemeEclipse.css" title="eclipse"/>
<link type="text/css" rel="alternate stylesheet" href="synh/styles/shThemeEclipse.css" title="eclipse"/>
<link type="text/css" rel="alternate stylesheet" href="synh/styles/shThemeEmacs.css" title="emacs"/>
<link type="text/css" rel="alternate stylesheet" href="synh/styles/shThemeFadeToGrey.css" title="fade to grey"/>
<link type="text/css" rel="alternate stylesheet" href="synh/styles/shThemeMidnight.css" title="midnight"/>
<link type="text/css" rel="alternate stylesheet" href="synh/styles/shThemeRDark.css" title="rdark"/>
<script type="text/javascript">SyntaxHighlighter.all();</script>
